// <auto-generated />
using AssignmentRectangleCorner.Repository.EFCore;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AssignmentRectangleCorner.Migrations
{
    [DbContext(typeof(TestCaseDbContext))]
    [Migration("20240614075940_Migration01")]
    partial class Migration01
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AssignmentRectangleCorner.Data.TestCase", b =>
                {
                    b.Property<int>("testcaseid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("testcaseid"));

                    b.Property<float>("answer")
                        .HasColumnType("real");

                    b.Property<string>("testcase")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("testcaseid");

                    b.ToTable("TestCases");
                });

            modelBuilder.Entity("AssignmentRectangleCorner.Model.TestCaseModel", b =>
                {
                    b.Property<int>("testcaseid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("testcaseid"));

                    b.Property<int>("Answer")
                        .HasColumnType("int");

                    b.Property<int>("Column")
                        .HasColumnType("int");

                    b.Property<int>("Row")
                        .HasColumnType("int");

                    b.Property<string>("TestCase")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("testcaseid");

                    b.ToTable("TestCaseModel");
                });
#pragma warning restore 612, 618
        }
    }
}
